version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ZenAdmin
      POSTGRES_PASSWORD: temp
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5445:5432"
volumes:
  postgres:
