version: '3'
services:
  postgres:
    image: timescale/timescaledb:1.7.2-pg12
    restart: always
    environment:
      POSTGRES_USER: ZenAdmin
      POSTGRES_PASSWORD: temp
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5445:5432"
volumes:
  postgres:
