kind: Deployment
apiVersion: apps/v1
metadata:
  name: zen-api
  labels:
    app: zen-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zen-api
  template:
    metadata:
      labels:
        app: zen-api
    spec:
      containers:
        - name: zen-api
          image: zenacr.azurecr.io/api:latest
          resources:
            requests:
              memory: "700Mi"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: DATABASE_URL
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: zen-jwt
                  key: privateKey
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: zen-jwt
                  key: publicKey
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zen-smtp
                  key: secret
            - name: SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: zen-smtp
                  key: SMTP_SERVER
            - name: SMTP_LOGIN
              valueFrom:
                secretKeyRef:
                  name: zen-smtp
                  key: SMTP_LOGIN
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zen-smtp
                  key: SMTP_PASSWORD
            - name: SMTP_FROM_NAME
              valueFrom:
                secretKeyRef:
                  name: zen-smtp
                  key: SMTP_FROM_NAME
            - name: SMTP_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: zen-smtp
                  key: SMTP_FROM_EMAIL
---
kind: Service
apiVersion: v1
metadata:
  name: zen-api-svc
spec:
  selector:
    app: zen-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zen-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://portal.site.ca"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zen-api-svc
            port:
              number: 80